databases:
  - name: consumer-app
    databaseName: consumer-app
    user: consumer-app

services:
  - type: web
    name: consumer-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: consumer-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false